name: Deploy to Netlify via Shared Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: clintoo/ci-pipelines/.github/workflows/deploy.yml@main
    with:
      environment: production
      url: https://xtremeart.netlify.app
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      PROD_ID: ${{ secrets.PROD_ID }}

  create-issue-on-failure:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - name: Create GitHub Issue on Failure
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = '🚨 Deployment Failed';
            const body = `The deployment job failed for branch: \`${{ github.ref }}\`.

            Please check the workflow runs and logs for details: [View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            cc @${{ github.actor }}`;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
            });
